//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplyRoutesPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApplyRoutesPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap DropDown8 {
            get {
                object obj = ResourceManager.GetObject("DropDown8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AR - Apply Route....
        /// </summary>
        internal static string Edit_ApplyRouteAction_Text {
            get {
                return ResourceManager.GetString("Edit_ApplyRouteAction_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Routes Plugin.
        /// </summary>
        internal static string Edit_ApplyRoutesPlugin_Text {
            get {
                return ResourceManager.GetString("Edit_ApplyRoutesPlugin_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AR - Create Routes From Activities....
        /// </summary>
        internal static string Edit_CreateRouteAction_Text {
            get {
                return ResourceManager.GetString("Edit_CreateRouteAction_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AR - Join  {0:S} {1:S}.
        /// </summary>
        internal static string Edit_JoinRoutesAction_Text {
            get {
                return ResourceManager.GetString("Edit_JoinRoutesAction_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route Manipulation.
        /// </summary>
        internal static string Edit_RouteManipulation_Text {
            get {
                return ResourceManager.GetString("Edit_RouteManipulation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AR - Send {0:S} {1:S} To Routes View.
        /// </summary>
        internal static string Edit_SendToRouteControl_Text {
            get {
                return ResourceManager.GetString("Edit_SendToRouteControl_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AR - Update History....
        /// </summary>
        internal static string Edit_UpdateEquipment_Text {
            get {
                return ResourceManager.GetString("Edit_UpdateEquipment_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        internal static string Generic_Activities_Text {
            get {
                return ResourceManager.GetString("Generic_Activities_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        internal static string Generic_Activity_Text {
            get {
                return ResourceManager.GetString("Generic_Activity_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One.
        /// </summary>
        internal static string Generic_One_Text {
            get {
                return ResourceManager.GetString("Generic_One_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three.
        /// </summary>
        internal static string Generic_Three_Text {
            get {
                return ResourceManager.GetString("Generic_Three_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two.
        /// </summary>
        internal static string Generic_Two_Text {
            get {
                return ResourceManager.GetString("Generic_Two_Text", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Map_Waypoint {
            get {
                object obj = ResourceManager.GetObject("Map_Waypoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Map_Waypoint_Hi {
            get {
                object obj = ResourceManager.GetObject("Map_Waypoint_Hi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Map_Waypoint_Sel {
            get {
                object obj = ResourceManager.GetObject("Map_Waypoint_Sel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Splits.
        /// </summary>
        internal static string MCL_SplitsMCL_Text {
            get {
                return ResourceManager.GetString("MCL_SplitsMCL_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AR - Routes.
        /// </summary>
        internal static string Route_Control_Title {
            get {
                return ResourceManager.GetString("Route_Control_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End: .
        /// </summary>
        internal static string Route_EndTime_Text {
            get {
                return ResourceManager.GetString("Route_EndTime_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start: .
        /// </summary>
        internal static string Route_StartTime_Text {
            get {
                return ResourceManager.GetString("Route_StartTime_Text", resourceCulture);
            }
        }
    }
}
